2019-04-16 12:45:39,986 ERROR: Exception on /index [POST] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\Sandra.cabrera\microblog\app\__init__.py", line 81, in get_locale
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
KeyError: 'LANGUAGES'
2019-04-16 12:45:43,789 ERROR: Exception on /index [POST] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\Sandra.cabrera\microblog\app\__init__.py", line 81, in get_locale
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
KeyError: 'LANGUAGES'
2019-04-16 12:45:54,013 ERROR: Exception on /index [GET] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\Sandra.cabrera\microblog\app\__init__.py", line 81, in get_locale
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
KeyError: 'LANGUAGES'
2019-04-16 12:45:54,953 ERROR: Exception on /index [GET] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\Sandra.cabrera\microblog\app\__init__.py", line 81, in get_locale
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
KeyError: 'LANGUAGES'
2019-04-16 12:45:57,222 ERROR: Exception on /auth/login [GET] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\Sandra.cabrera\microblog\app\__init__.py", line 81, in get_locale
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
KeyError: 'LANGUAGES'
2019-04-16 12:46:01,162 ERROR: Exception on /index [GET] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\Sandra.cabrera\microblog\app\__init__.py", line 81, in get_locale
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
KeyError: 'LANGUAGES'
2019-04-16 12:46:18,515 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
